WIFI_SSID = "BAJOBONGO"
WIFI_PASSWORD = "manhattan"

INFLUXDB_TOKEN = "ImLK5eHBi4CZqCe9NgUIHgqkTOwM_2kyiGVMBhUFwESDVGr4qMbu9kDdCBXdXC09gykXpXtLIs0E-tnkiArVmg=="
INFLUXDB_HOST = "192.168.1.25"
INFLUXDB_PORT = "8086"
INFLUXDB_ORG = "home"
INFLUXDB_BUCKET = "temp_humidity_pressure"
